const constants = {
  RESET_GAME: "RESET_GAME",
  ADD_USER_INPUT: "ADD_USER_INPUT",
  ADD_AI_INPUT: "ADD_AI_INPUT",
  SET_GAME_DONE: "SET_GAME_DONE",
  SET_WINNER: "SET_WINNER",
  SET_TOKEN: "SET_TOKEN",
  CLEAR_TOKEN: "CLEAR_TOKEN"

};

export default constants;
